local_backend: true
backend:
  name: github
  branch: main
  repo: newscorp-ghfb/newskit/
media_folder: public/static
public_folder: public/static
collections:
  - name: "docs"
    label: "Docs"
    folder: 'content/'
    extension: "mdx"
    format: "frontmatter"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "intro"
        name: "intro" 
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Type"
            name: "type"
            widget: "string"
          - label: "Cover Image"
            name: "coverImage"
            type: "image"
          - label: "Introduction"
            name: "introduction"
            widget: "text"